### ISSUE TITLE
This is a gem! 💎

### ISSUE THREAD

**Issue by sam-hosseini** [rikukissa/osinkoavaipalkkaa.fi#11]
Hi Riku! 👋🏼

I don't even know where to start, wow, this is a fantastic website!! 👏🏼

Everytime I've been looking into optimizating the ratio of salary vs dividend, I was like "why on earth don't we have a simple frontend calculator that has done the heavy lifting of these calculations?" and because I didn't have much frontend skills nor the determination to run the numbers properly 😅, it remained a wish until a friend told me about this.

So thanks a lot for having done that and sharing it publicly for everyone!

Is there any chance you would be able to translate it to English too? (my Finnish is not that good, otherwise I'd have opened a PR)

The reason I'm asking is that I think this website would be a great addition to the [Take out money from your company in the most tax optimal way section of Freelancing in Finland guide](https://github.com/sam-hosseini/freelancing-in-finland#take-out-money-from-your-company-in-the-most-tax-optimal-way). I already added the calculator to the references section (https://github.com/sam-hosseini/freelancing-in-finland/commit/02451c7b056becb184c2f6e2c113dfa09c9cb6f4) 

I'll share this with my friends and peers to see if it sparks other people's interest as well to translate this.

Thank you again 🍁

**Comment by rikukissa** [comment]
Hi Sam! 👋

Thanks for your encouraging words and great to hear you find it useful. This was originally created as I found Excel to get a bit too complex while I was trying to crunch these numbers. Another thing is getting the formulas 100% right, which still seems to require some tuning as per the other PR. 

I'll look into translating this to English this weekend and maybe I'll clean up some of that code as well so other people would be able to contribute as well 😎

Thanks for reaching out and tell your friend I said hi 😄

**Comment by sam-hosseini** [comment]
Closing this now that the website is translated after https://github.com/rikukissa/osinkoavaipalkkaa.fi/pull/14, gratzie mille 👌🏼
