### ISSUE TITLE
Yhteisövero pitäisi huomioida vain siltä osalta, joka maksetaan osinkona

### ISSUE THREAD

**Issue by Ballhorn** [rikukissa/osinkoavaipalkkaa.fi#12]
Palkkaa ja osinkoa vertailtaessa maksetusta yhteisöverosta pitäisi huomioida ainoastaan se osuus, joka liittyy maksettuihin osinkohin. Taseeseen jäävästä osuudesta maksettu yhteisövero ei ole laskelman kannalta relevantti.

En myöskään huomioisi tuloksen aiheuttamaa nettovarallisuuden muutosta, koska se vaikuttaa verotuksessa vasta seuraavana verovuonna.

**Comment by rikukissa** [comment]
Katselen viikonloppuna näihin korjauksen, ja pingailen vaikka sinua tarkastamaan, että menee varmasti oikein 👍  Koko projektissa on vielä(kin) parannettavaa siinä miten numerot esitetään ja miten ne saadaan "tuntumaan" heti oikeilta, ja sitten toki myös kaavoissa itsessään. Esimerkiksi nuo tuloveroprosentit mihin laskukaavat perustuu voisi olla esillä jossain kohtaa sivua.

Kiitos kommentista!

**Comment by rikukissa** [comment]
Ymmärränkö oikein, että viittaat yhteisöveron tarpeettomuudella laskelmissa siihen, että edellisten tilikausien tappioita voidaan vähentää nykyisen voitosta ja toisin päin? Eli käytännössä vuositasolla maksetun yhteisöveron määrän tarkkailu on turhaa sillä tilanne voi muuttua tulevina vuosina. Tämä tuli itselleni uutena tietona. 

Tällä hetkellä vertailu ja laskutoimitukset toimii kokonaisveron määrän mukaan (tulovero + pääomatulovero + yhteisövero):
https://github.com/rikukissa/osinkoavaipalkkaa.fi/blob/master/src/formulas.ts#L89-L100

Kokeilin kommenttisi pohjalta pudottaa yhteisöveron vertailusta pois kokonaan. Huomasin, että "Edullisin vaihtoehto" joka skenaariossa on tällöin 0€ osinkoa ja 0€ palkkaa, joka sinäänsä käy ihan järkeen. 
Alkuperäinen ajatus yhteisöveron ottamiselle mukaan oli tilanne, jossa yrityksen voitosta (esim. 100 000 €) voidaan nostaa 0% tuloveroprosentilla pois 14 000 €, jolloin yhteisöveron määräksi tulee `(100 000 - 14 000) * 0.2 = 17 200 €` kun taas nostamalla 0€ palkkaa yhteisöveron määräksi tulisi 20 000 €.

[Verottajan veroprosenttilaskurista](https://www.vero.fi/henkiloasiakkaat/verokortti-ja-veroilmoitus/verokortti/veroprosenttilaskuri/) crawlatut tuloveroprosentit löytyy täältä:
https://github.com/rikukissa/osinkoavaipalkkaa.fi/blob/master/src/income-tax.ts

**Comment by Ballhorn** [comment]
Tarkoitin, että yhteisövero tulisi huomioida vain siltä osalta, joka maksetaan ulos osinkona ts. seurataan sitä, kuinka paljon maksetaan veroa yhtiöstä ulos maksetuista euroista.

Esim: 100 000 nettovarallisuus, 100 000 tuotot ennen palkkoja, bruttopalkkaa 14 000 ja brutto-osinkoja 8 000,
palkkavero 0 ja yhteisövero 17 200. Osingot 8% nettovarallisuudesta (tilikauden alussa, verotuksessa vahvistettu arvo), joten osinkovero 8 000 * 0,25 * 0,30 = 600. Osinkona maksetusta 8 000 voitosta yritys on maksanut yhteisöveroa 8 000 / 0,8 * 0,2 = 2 000.
Ansiotulovero 0
Pääomatulovero 600
Yhteisövero 2 000

Taseeseen jääneestä voitosta maksettu yhteisövero 15 200 ei liity yksittäisen vuoden palkka vai osinko -vertailuun. Samaa johtoajatusta noudattaen pitäisi tilanteessa, jossa maksetaan osinkoja yli tilikauden voiton, ottaa laskelmassa mukaan yhteisövero, joka on maksettu nyt ulos maksettavista kertyneistä voittovaroista. Näyttäisin sen osuuden omalla rivillään esimerkiksi nimikkeellä 'Aiemmin maksettu yhteisövero'.

**Comment by rikukissa** [comment]
Jees, uskon ymmärtäneeni. Muutin nyt vertailua niin, että yhden skenaarion kokonaisveron määrä lasketaan `ansiotulovero + pääomatulovero + yhteisövero osinkojen määrästä`.

Uutta versiota pääsee katsomaan täältä:
https://deploy-preview-13--tender-roentgen-cd6e75.netlify.app/

Miltä omaan silmääsi vaikuttaa?

**Comment by Ballhorn** [comment]
Yhteisövero tulee nyt oikein. Muuttaisin otsikon pelkäksi yhteisöveroksi ja selvittäisin esittelytekstissä tai tooltipissä, että yhteisövero huomioidaan ainoastaan osinkona maksetun tulon osalta.

Pääomatulovero vaikuttaa jäävän hieman matalaksi. Nostaako yrityksen tulos vielä nettovarallisuutta?

Ansiotulovero tulee väärin, koska income-tax.ts:n palkat eivät ole suuruusjärjestyksessä.

**Comment by rikukissa** [comment]
Koitin dekryptata vähän tuota omaa pääomatuloveron laskentakaavaa. Esimerkkinä vaikka `100 000 €` nettovarallisuus ja `9000 €` osingot. Jos nyt tulkitsen tätä oikein

https://www.veronmaksajat.fi/Sijoittaminen/Osinkojen-verotus/#:~:text=Tavallisen%20osakes%C3%A4%C3%A4st%C3%A4j%C3%A4n%20saama%20osinko%20on,osasta%20menee%20veroa%2030%20prosenttia.

niin kaava olisi kutakuinkin 

```
(8000 * 0.25 * 0.3) + (1000 * 0.75 * 0.3) = 825 €
```

eli vaikuttaisi olevan kunnossa tai tulkitsen ohjetta väärin. Tämä siis perustuen 

>Osingosta, joka vastaa enintään 8 % osakkeen matemaattisesta arvosta, on 25 % veronalaista pääomatuloa. Tällaista osinkoa voi yksi henkilö saada vuodessa enintään 150 000 euroa. Sen ylittävästä osingosta veronalaista pääomatuloa on 85 %.
> Osingosta, joka ylittää 8 % osakkeen matemaattisesta arvosta, on 75 % veronalaista ansiotuloa. Osakkeen matemaattinen arvo on yhtiön nettovarallisuus jaettuna ulkona olevien osakkeiden määrällä. Se lasketaan osingon jakovuotta edellisen vuoden tilinpäätöksestä.

Yrityksen tulos ei nosta nettovarallisuutta. 

Hyvä huomio income-tax.ts:stä. Nuo nyt korjattu 👍

**Comment by Ballhorn** [comment]
Nyt vaikuttaa luvut oikeilta. Pääomaverokommentti oli mun laskuvirhe.

**Comment by rikukissa** [comment]
Loistavaa! Kiitos paljon avusta :)

**Comment by huuhtaneno** [comment]
Ymmärsinkö oikein, että laskuri laskee 8% ylittävän osuuden myös pääomatuloksi? Ymmärtääkseni näinhän se ei ole? Vai olenko ymmärtänyt jotain täysin vääri?

**Comment by rikukissa** [comment]
Tarkoitatko, että se tulisi laskea ansiotulona? Taidat olla oikeassa nyt kun tuota https://www.veronmaksajat.fi/Sijoittaminen/Osinkojen-verotus/#bed8e2d5 luen vielä tarkemmin

>Osingosta, joka ylittää 8 % osakkeen matemaattisesta arvosta, on 75 % veronalaista ansiotuloa. Osakkeen matemaattinen arvo on yhtiön nettovarallisuus jaettuna ulkona olevien osakkeiden määrällä. Se lasketaan osingon jakovuotta edellisen vuoden tilinpäätöksestä.

**Comment by huuhtaneno** [comment]
Juurikin niin.

**Comment by rikukissa** [comment]
Hyvä huomio 👍  Fiksaan asap

**Comment by huuhtaneno** [comment]
Hienoa! En siis ollut ymmärtänyt väärin 👍

**Comment by rikukissa** [comment]
@huuhtaneno Voisitko tsekata miltä laskelmat nyt vaikuttaisi:
https://github.com/rikukissa/osinkoavaipalkkaa.fi/pull/18

**Comment by rikukissa** [comment]
@Ballhorn pakko vielä häiritä sinuakin. Mitä olet mieltä tällaisesta tapauksesta:

Nettovarallisuus: 500 000 €
Ennuste voitosta: 100 000 €
Nettotulon alaraja: 30 000 €

Käyttäjälle ehdotetaan 5000€ osinkoa ja 30 000€ bruttopalkkaa:

![image](https://user-images.githubusercontent.com/1206987/96604514-e1d83180-12fd-11eb-8dde-c85b8dc729f6.png)

Näistä menisi veroa siis 5 825 € yhteensä mukaan lukien jo maksetun yhteisöveron osingosta. 

Korkeamman osingon vaihtoehdossa veroja maksettaisiin 14 250 €
![image](https://user-images.githubusercontent.com/1206987/96604747-1e0b9200-12fe-11eb-870c-dd0000be6e53.png)

Ilman osingosta laskettua yhteisöveroa nämä vertautuisi keskenään kuitenkin 4575 € vs 3375 €, eli osingon määrää nostamalla maksettaisiin vähemmän muita veroja. 

Ehkä kysymys tiivistyy siihen, että onko yhteisöveron laskeminen mukaan nostettaviin osinkoihin, mutta ei palkkaan kaikissa tilanteissa reilu vertailu? Palkan nostamisen puolesta toki puhuu kyseisen tilikauden yhteisöveron laskeminen 🤔

**Comment by Ballhorn** [comment]
On se siinä mielessä reilu vertailu, että yrityksen liikevaihtona saamasta eurosta palkkana maksettaessa veroja maksetaan ainoastaan ansiotulosta. Osinkojen kohdalla samasta eurosta maksetaan ensin yhteisövero ja sen jälkeen osinkoverotuksen mukainen summa.

Tietysti vaihtoehdoissa on se periaatteelinen ero, että osinkoja maksetaan lähtökohtaisesti aikaisempien tilikausien kertyneistä voittovaroista, kun palkka kohdistuu kuluvaan tilikauteen. Moni yrittäjä kuitenkin katsoo kuluvaa tilikautta ja miettii, mikä olisi optimaalinen yhdistelmä.

Tilikauden voitosta maksettu yhteisövero on tavallaan ennakkoon maksettua tulevien osinkojen veroa. Se ei ole vielä realisoitunut yrittäjän näkökulmasta, koska yrittäjä ei vielä ole saanut sitä vastaavaa tuloa.

Yksinyrittäjän kohdalla huojennetun osingon ylittävät osingot ovat kalliita, eli kuvan optimi vaikuttaa olevan melko järkevässä kohdassa. Sen tosin luulisi olevan 8 000 eikä 5 000  euron kohdalla.
